### ISSUE TITLE
Version on prank.codes broken

### ISSUE THREAD

**Issue by BastelPichi** [amirmaula/discord-prank#3]
When generating a image, an error that uploading wasnt possible is shown.

**Comment by amirldn** [comment]
Hey BastelPichi,

I also get the same thing - let me have a look and try fix this bug.

**Comment by amirldn** [comment]
Fixed :)

**Comment by amirldn** [comment]
The reason why this was broken is because imgbb (the previous image host) banned my API key and my IP (not sure if this was due to me or repl.it) - I switched over to imgur and improved the logging a bit too on the site so I can spot these errors a little easier in future.
